# Generated by Django 6.0.1 on 2026-04-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mtoaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina_la_kwanza', models.CharField(default='Hana', max_length=255)),
                ('jina_la_mwisho', models.CharField(default='Jina', max_length=255)),
                ('ushirika', models.CharField(choices=[('M', 'Mshiriki'), ('S', 'Sio_Mshiriki')], default='M')),
                ('namba_ya_ushirika', models.IntegerField(default=0)),
                ('simu', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
