# Generated by Django 6.0 on 2026-01-13 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ainayamatoleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aina', models.CharField(choices=[('Z', 'Zaka'), ('S', 'Sadaka'), ('I', 'Idara'), ('M', 'Matoleo mengine')], default='I', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Idara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idara', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mtoaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina_la_kwanza', models.CharField(default='john', max_length=255)),
                ('jina_la_mwisho', models.CharField(default='doe', max_length=255)),
                ('ushirika', models.CharField(default='sio mshiriki', max_length=255)),
                ('namba_ya_ushirika', models.IntegerField(default=0, max_length=5)),
                ('simu', models.FloatField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matoleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiasi', models.DecimalField(decimal_places=2, max_digits=30)),
                ('ainayamatoleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hazina.ainayamatoleo')),
                ('idara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hazina.idara')),
                ('mtoaji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hazina.mtoaji')),
            ],
        ),
    ]
