# Generated by Django 6.0.1 on 2026-03-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtoaji',
            name='namba_ya_ushirika',
            field=models.IntegerField(default=0),
        ),
    ]
