# Generated by Django 6.0.1 on 2026-04-01 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Watoaji', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina', models.CharField(default='Huduma za washiriki', max_length=255)),
                ('asilimia', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Matoleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiasi', models.DecimalField(decimal_places=2, max_digits=30)),
                ('aina', models.CharField(default='zaka', max_length=100)),
                ('tarehe', models.DateTimeField(auto_now=True)),
                ('jina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Watoaji.mtoaji')),
                ('jina_la_idara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matoleo.idara')),
            ],
        ),
    ]
