# Generated by Django 6.0.1 on 2026-04-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matoleo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idara',
            name='asilimia',
        ),
    ]
